Update conexao

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -290,20 +290,20 @@ fi
 
 fun_squid() {
 [[ "$(netstat -nplt | grep -c 'squid')" = "0" ]] && inst_sqd
-echo -e "\E[44;1;37m          GERENCIAR SQUID PROXY           \E[0m"
+echo -e "\E[44;1;37m          MANAGE SQUID PROXY           \E[0m"
 [[ "$(netstat -nplt | grep -c 'squid')" != "0" ]] && {
 sqdp=$(netstat -nplt | grep 'squid' | awk -F ":" {'print $4'} | xargs)
-echo -e "\n\033[1;33mPORTAS\033[1;37m: \033[1;32m$sqdp"
-VarSqdOn="ลบ SQUID PROXY"
+echo -e "\n\033[1;33mPORT\033[1;37m: \033[1;32m$sqdp"
+VarSqdOn="Delete SQUID PROXY"
 } || {
-VarSqdOn="INSTALAR SQUID PROXY"
+VarSqdOn="INSTALL SQUID PROXY"
 }
 echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33m$VarSqdOn \033[1;31m
 [\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mAdd port \033[1;31m
 [\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mDelete port\033[1;31m
 [\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mCancel\033[0m"
 echo ""
-echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m "
+echo -ne "\033[1;32mWHAT DO YOU WANT TO DO \033[1;33m?\033[1;31m?\033[1;37m "
 read x
 clear
 case $x in
@@ -317,12 +317,12 @@ addpt_sqd
 rempt_sqd
 ;;
 0 | 00)
-echo -e "\033[1;31mRetornando...\033[0m"
+echo -e "\033[1;31mReturning...\033[0m"
 sleep 1
 fun_conexao
 ;;
 *)
-echo -e "\033[1;31mOpcao Invalida...\033[0m"
+echo -e "\033[1;31mInvalid option...\033[0m"
 sleep 2
 fun_conexao
 ;;
@@ -806,7 +806,7 @@ fi
 
 fun_openvpn() {
 if readlink /proc/$$/exe | grep -qs "dash"; then
-echo "Este script precisa ser executado com bash, não sh"
+echo "This script needs to be run with bash, not sh"
 exit 1
 fi
 [[ "$EUID" -ne 0 ]] && {
@@ -815,12 +815,12 @@ echo "Execulte como root"
 exit 2
 }
 [[ ! -e /dev/net/tun ]] && {
-echo -e "\033[1;31mTUN TAP NAO DISPONIVEL\033[0m"
+echo -e "\033[1;31mTUN TAP NOT AVAILABLE\033[0m"
 sleep 2
 exit 3
 }
 if grep -qs "CentOS release 5" "/etc/redhat-release"; then
-echo "O CentOS 5 é muito antigo e não é suportado"
+echo "CentOS 5 is too old and not supported"
 exit 4
 fi
 if [[ -e /etc/debian_version ]]; then
@@ -832,7 +832,7 @@ OS=centos
 GROUPNAME=nobody
 RCLOCAL='/etc/rc.d/rc.local'
 else
-echo -e "SISTEMA NAO SUPORTADO"
+echo -e "SYSTEM NOT SUPPORTED"
 exit 5
 fi
 newclient() {
@@ -873,9 +873,9 @@ mult=$(echo -e "\033[1;32m◉ ")
 else
 mult=$(echo -e "\033[1;31m○ ")
 fi
-echo -e "\E[44;1;37m          GERENCIAR OPENVPN           \E[0m"
+echo -e "\E[44;1;37m          TO MANAGE OPENVPN           \E[0m"
 echo ""
-echo -e "\033[1;33mPORTA\033[1;37m: \033[1;32m$opnp"
+echo -e "\033[1;33mPORT\033[1;37m: \033[1;32m$opnp"
 echo ""
 echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mChange port"
 echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mReset OpenVPN"
@@ -884,26 +884,26 @@ echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mConnect multi
 echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mChange HOST DNS"
 echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mGo back"
 echo ""
-echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m "
+echo -ne "\033[1;32mWHAT DO YOU WANT TO DO \033[1;33m?\033[1;31m?\033[1;37m "
 read option
 case $option in
 1)
 clear
-echo -e "\E[44;1;37m         ALTERAR PORTA OPENVPN         \E[0m"
+echo -e "\E[44;1;37m         CHANGE PORT OPENVPN         \E[0m"
 echo ""
 echo -e "\033[1;33mPORTA EM USO: \033[1;32m$opnp"
 echo ""
-echo -ne "\033[1;32mQUAL PORTA DESEJA UTILIZAR \033[1;33m?\033[1;37m "
+echo -ne "\033[1;32mWHICH PORT DO YOU WANT TO USE \033[1;33m?\033[1;37m "
 read porta
 [[ -z "$porta" ]] && {
 echo ""
-echo -e "\033[1;31mPorta invalida!"
+echo -e "\033[1;31mInvalid port!"
 sleep 3
 fun_conexao
 }
 verif_ptrs
 echo ""
-echo -e "\033[1;32mALTERANDO A PORTA OPENVPN!\033[1;33m"
+echo -e "\033[1;32mCHANGING THE OPENVPN PORT!\033[1;33m"
 echo ""
 fun_opn() {
 var_ptovpn=$(sed -n '1 p' /etc/openvpn/server.conf)
@@ -916,13 +916,13 @@ service openvpn restart
 }
 fun_bar 'fun_opn'
 echo ""
-echo -e "\033[1;32mPORTA ALTERADA COM SUCESSO!\033[1;33m"
+echo -e "\033[1;32mPORT CHANGED SUCCESSFULLY!\033[1;33m"
 sleep 2
 fun_conexao
 ;;
 2)
 echo ""
-echo -ne "\033[1;32mDESEJA REMOVER O OPENVPN \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+echo -ne "\033[1;32mWANT TO REMOVE OPENVPN \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
 read REMOVE
 [[ "$REMOVE" = 's' ]] && {
 rmv_open() {
@@ -963,16 +963,16 @@ rm -rf /etc/openvpn
 rm -rf /usr/share/doc/openvpn*
 }
 echo ""
-echo -e "\033[1;32mREMOVENDO O OPENVPN!\033[0m"
+echo -e "\033[1;32mREMOVING OPENVPN!\033[0m"
 echo ""
 fun_bar 'rmv_open'
 echo ""
-echo -e "\033[1;32mOPENVPN REMOVIDO COM SUCESSO!\033[0m"
+echo -e "\033[1;32mOPENVPN SUCCESSFULLY REMOVED!\033[0m"
 sleep 2
 fun_conexao
 } || {
 echo ""
-echo -e "\033[1;31mRetornando...\033[0m"
+echo -e "\033[1;31mReturning...\033[0m"
 sleep 2
 fun_conexao
 }
@@ -997,7 +997,7 @@ done
 done
 tput cnorm
 }
-echo -ne "\033[1;31mDESATIVANDO\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
+echo -ne "\033[1;31mDEACTIVING\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
 helice
 echo -e "\e[1DOk"
 }
@@ -1032,7 +1032,7 @@ done
 done
 tput cnorm
 }
-echo -ne "\033[1;32mATIVANDO\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
+echo -ne "\033[1;32mACTIVATING\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
 helice
 echo -e "\e[1DOk"
 }
@@ -1062,7 +1062,7 @@ done
 tput cnorm
 }
 echo ""
-echo -ne "\033[1;31mBLOQUEANDO MULTILOGIN\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
+echo -ne "\033[1;31mBLOCKING MULTILOGIN\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
 helice
 echo -e "\e[1DOk"
 }
@@ -1090,7 +1090,7 @@ done
 tput cnorm
 }
 echo ""
-echo -ne "\033[1;32mPERMITINDO MULTILOGIN\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
+echo -ne "\033[1;32mALLOWED MULTILOGIN\033[1;32m.\033[1;33m.\033[1;31m. \033[1;33m"
 helice
 echo -e "\e[1DOk"
 }
@@ -1101,18 +1101,18 @@ fi
 ;;
 5)
 clear
-echo -e "\E[44;1;37m         ALTERAR HOST DNS           \E[0m"
+echo -e "\E[44;1;37m         TO ALTER HOST DNS           \E[0m"
 echo ""
 echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mADICIONAR HOST DNS"
 echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVER HOST DNS"
 echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mEDITAR MANUALMENTE"
 echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR"
 echo ""
-echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m "
+echo -ne "\033[1;32mWHAT DO YOU WANT TO DO \033[1;33m?\033[1;31m?\033[1;37m "
 read resp
 [[ -z "$resp" ]] && {
 echo ""
-echo -e "\033[1;31mOpcao invalida!"
+echo -e "\033[1;31mInvalid option!"
 sleep 3
 fun_openvpn
 }
@@ -1120,29 +1120,29 @@ if [[ "$resp" = '1' ]]; then
 clear
 echo -e "\E[44;1;37m            Adicionar Host DNS            \E[0m"
 echo ""
-echo -e "\033[1;33mLista dos hosts atuais:\033[0m "
+echo -e "\033[1;33mList of current hosts:\033[0m "
 echo ""
 i=0
 for _host in $(grep -w "127.0.0.1" /etc/hosts | grep -v "localhost" | cut -d' ' -f2); do
 echo -e "\033[1;32m$_host"
 done
 echo ""
-echo -ne "\033[1;33mDigite o host a ser adicionado\033[1;37m : "
+echo -ne "\033[1;33mEnter the host to add\033[1;37m : "
 read host
 if [[ -z $host ]]; then
 echo ""
-echo -e "\E[41;1;37m        Campo Vazio ou invalido !       \E[0m"
+echo -e "\E[41;1;37m        Empty or invalid field !       \E[0m"
 sleep 2
 fun_openvpn
 fi
 if [[ "$(grep -w "$host" /etc/hosts | wc -l)" -gt "0" ]]; then
-echo -e "\E[41;1;37m    Esse host ja está adicionado  !    \E[0m"
+echo -e "\E[41;1;37m    This host is already added  !    \E[0m"
 sleep 2
 fun_openvpn
 fi
 sed -i "3i\127.0.0.1 $host" /etc/hosts
 echo ""
-echo -e "\E[44;1;37m      Host adicionado com sucesso !      \E[0m"
+echo -e "\E[44;1;37m      Host added successfully !      \E[0m"
 sleep 2
 fun_openvpn
 elif [[ "$resp" = '2' ]]; then
@@ -1160,7 +1160,7 @@ oP+=":$_host\n"
 echo -e "\033[1;33m[\033[1;31m$i\033[1;33m] \033[1;37m- \033[1;32m$_host\033[0m"
 done
 echo ""
-echo -ne "\033[1;32mSelecione o host a ser removido \033[1;33m[\033[1;37m1\033[1;31m-\033[1;37m$i\033[1;33m]\033[1;37m: "
+echo -ne "\033[1;32mSelect the host to remove \033[1;33m[\033[1;37m1\033[1;31m-\033[1;37m$i\033[1;33m]\033[1;37m: "
 read option
 if [[ -z $option ]]; then
 echo ""
@@ -1172,27 +1172,27 @@ host=$(echo -e "$oP" | grep -E "\b$option\b" | cut -d: -f2)
 hst=$(grep -v "127.0.0.1 $host" /etc/hosts)
 echo "$hst" >/etc/hosts
 echo ""
-echo -e "\E[41;1;37m      Host removido com sucesso !      \E[0m"
+echo -e "\E[41;1;37m      Host removed successfully !      \E[0m"
 sleep 2
 fun_openvpn
 elif [[ "$resp" = '3' ]]; then
-echo -e "\n\033[1;32mALTERANDO ARQUIVO \033[1;37m/etc/hosts\033[0m"
-echo -e "\n\033[1;31mATENCAO!\033[0m"
-echo -e "\n\033[1;33mPARA SALVAR USE AS TECLAS \033[1;32mctrl x y\033[0m"
+echo -e "\n\033[1;32mCHANGING FILE \033[1;37m/etc/hosts\033[0m"
+echo -e "\n\033[1;31mATTENTION!\033[0m"
+echo -e "\n\033[1;33mTO SAVE USE THE KEYS \033[1;32mctrl x y\033[0m"
 sleep 4
 clear
 nano /etc/hosts
-echo -e "\n\033[1;32mALTERADO COM SUCESSO!\033[0m"
+echo -e "\n\033[1;32mCHANGED SUCCESSFULLY!\033[0m"
 sleep 3
 fun_openvpn
 elif [[ "$resp" = '0' ]]; then
 echo ""
-echo -e "\033[1;31mRetornando...\033[0m"
+echo -e "\033[1;31mReturning...\033[0m"
 sleep 2
 fun_conexao
 else
 echo ""
-echo -e "\033[1;31mOpcao invalida !\033[0m"
+echo -e "\033[1;31mInvalid option !\033[0m"
 sleep 2
 fun_openvpn
 fi
@@ -1202,7 +1202,7 @@ fun_conexao
 ;;
 *)
 echo ""
-echo -e "\033[1;31mOpcao invalida !\033[0m"
+echo -e "\033[1;31mInvalid option !\033[0m"
 sleep 2
 fun_openvpn
 ;;
@@ -1210,32 +1210,32 @@ esac
 done
 } || {
 clear
-echo -e "\E[44;1;37m              INSTALADOR OPENVPN               \E[0m"
+echo -e "\E[44;1;37m              OPENVPN INSTALLER               \E[0m"
 echo ""
-# OpenVPN instalador e criação do primeiro usuario
-echo -e "\033[1;33mRESPONDA AS QUESTOES PARA INICIAR A INSTALACAO"
+# OpenVPN installer and creation of the first user
+echo -e "\033[1;33mANSWER THE QUESTIONS TO START THE INSTALLATION"
 echo ""
-echo -ne "\033[1;32mPARA CONTINUAR CONFIRME SEU IP: \033[1;37m"
+echo -ne "\033[1;32mTO CONTINUE CONFIRM YOUR IP: \033[1;37m"
 read -e -i $IP IP
 [[ -z "$IP" ]] && {
 echo ""
-echo -e "\033[1;31mIP invalido!"
+echo -e "\033[1;31mIP invalid!"
 sleep 3
 fun_conexao
 }
 echo ""
-read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m")" -e -i 443 porta
+read -p "$(echo -e "\033[1;32mWHICH PORT DO YOU WANT TO USE? \033[1;37m")" -e -i 443 porta
 [[ -z "$porta" ]] && {
 echo ""
-echo -e "\033[1;31mPorta invalida!"
+echo -e "\033[1;31mInvalid port!"
 sleep 2
 fun_conexao
 }
 echo ""
-echo -e "\033[1;33mVERIFICANDO PORTA..."
+echo -e "\033[1;33mCHECKING PORT..."
 verif_ptrs $porta
 echo ""
-echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mSistema"
+echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mSystem"
 echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mGoogle (\033[1;32mRecomendado\033[1;33m)"
 echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;33mOpenDNS"
 echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;33mCloudflare"
@@ -1243,12 +1243,12 @@ echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;33mHurricane Electric"
 echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;33mVerisign"
 echo -e "\033[1;31m[\033[1;36m7\033[1;31m] \033[1;33mDNS Performace\033[0m"
 echo ""
-read -p "$(echo -e "\033[1;32mQUAL DNS DESEJA UTILIZAR? \033[1;37m")" -e -i 2 DNS
+read -p "$(echo -e "\033[1;32mWHICH DNS DO YOU WANT TO USE? \033[1;37m")" -e -i 2 DNS
 echo ""
 echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;33mUDP"
-echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mTCP (\033[1;32mRecomendado\033[1;33m)"
+echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;33mTCP (\033[1;32mRecommended\033[1;33m)"
 echo ""
-read -p "$(echo -e "\033[1;32mQUAL PROTOCOLO DESEJA UTILIZAR NO OPENVPN? \033[1;37m")" -e -i 2 resp
+read -p "$(echo -e "\033[1;32mWHICH PROTOCOL DO YOU WANT TO USE IN OPENVPN? \033[1;37m")" -e -i 2 resp
 if [[ "$resp" = '1' ]]; then
 PROTOCOL=udp
 elif [[ "$resp" = '2' ]]; then
@@ -1258,7 +1258,7 @@ PROTOCOL=tcp
 fi
 echo ""
 [[ "$OS" = 'debian' ]] && {
-echo -e "\033[1;32mATUALIZANDO O SISTEMA"
+echo -e "\033[1;32mUPDATING THE SYSTEMUPDATING THE SYSTEM"
 echo ""
 fun_attos() {
 apt-get update-y
@@ -1266,7 +1266,7 @@ apt-get upgrade -y
 }
 fun_bar 'fun_attos'
 echo ""
-echo -e "\033[1;32mINSTALANDO DEPENDENCIAS"
+echo -e "\033[1;32mINSTALLING DEPENDENCIES"
 echo ""
 fun_instdep() {
 apt-get install openvpn iptables openssl ca-certificates -y
@@ -1427,7 +1427,7 @@ fi
 fi
 fi
 }
-echo -e "\033[1;32mINSTALANDO O OPENVPN  \033[1;31m(\033[1;33mPODE DEMORAR!\033[1;31m)"
+echo -e "\033[1;32mINSTALLING OPENVPN  \033[1;31m(\033[1;33mIT MAY TAKE A LONG TIME!\033[1;31m)"
 echo ""
 fun_bar 'fun_dep > /dev/null 2>&1'
 fun_bar 'nginx_sm > /dev/null 2>&1'
@@ -1452,7 +1452,7 @@ fi
 }
 }
 echo ""
-echo -e "\033[1;32mREINICIANDO O OPENVPN"
+echo -e "\033[1;32mRESTART OPENVPN"
 echo ""
 fun_bar 'fun_ropen'
 IP2=$(wget -4qO- "http://whatismyip.akamai.com/")
@@ -1485,9 +1485,9 @@ cipher none
 comp-lzo
 script-security 3
 EOF
-# สร้าง client.ovpn
-newclient "SPNET"
-[[ "$(netstat -nplt | grep -wc 'openvpn')" != '0' ]] && echo -e "\n\033[1;32mOPENVPN INSTALADO COM SUCESSO\033[0m" || echo -e "\n\033[1;31mERRO ! A INSTALACAO CORROMPEU\033[0m"
+# build client.ovpn
+newclient "SKS"
+[[ "$(netstat -nplt | grep -wc 'openvpn')" != '0' ]] && echo -e "\n\033[1;32mOPENVPN INSTALLED SUCCESSFULLY\033[0m" || echo -e "\n\033[1;31mERROR ! THE INSTALLATION HAS BEEN BREAK\033[0m"
 }
 sed -i '$ i\echo 1 > /proc/sys/net/ipv4/ip_forward' /etc/rc.local
 sed -i '$ i\echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6' /etc/rc.local
@@ -1503,7 +1503,7 @@ fun_conexao
 
 fun_socks() {
 clear
-echo -e "\E[44;1;37m            GERENCIAR PROXY SOCKS             \E[0m"
+echo -e "\E[44;1;37m            MANAGE PROXY SOCKS             \E[0m"
 echo ""
 [[ $(netstat -nplt | grep -wc 'python') != '0' ]] && {
 sks='\033[1;32mON'
@@ -1519,11 +1519,11 @@ echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSOCKS SSH $va
 echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET $var_sks2 \033[0m"
 echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mSOCKS OPENVPN $sksop \033[0m"
 echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA\033[0m"
-echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mเปลี่ยน STATUS SOCKS SSH\033[0m"
-echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mเปลี่ยน STATUS WEBSOCKET\033[0m"
-echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mย้อนกลับ\033[0m"
+echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mChange STATUS SOCKS SSH\033[0m"
+echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mChange STATUS WEBSOCKET\033[0m"
+echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mCancel\033[0m"
 echo ""
-echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
+echo -ne "\033[1;32mWHAT DO YOU WANT TO DO \033[1;33m?\033[1;37m "
 read resposta
 if [[ "$resposta" = '1' ]]; then
 if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
